### ISSUE TITLE
Installing failure via chicken-install

### ISSUE THREAD

**Issue by nsjph** [zilti/chicken-edn#1]
I have Chicken 4.9.0.1 on Ubuntu 14.04 x86-64.

I cloned this repo and ran "chicken-install" from inside the cloned directory.

It failed to complete until I added (import chicken) to top of edn-impl.scm.

**Comment by zilti** [comment]
Thanks; I fixed this. Will release it as soon as the issue with edn->alist is fixed.

**Comment by zilti** [comment]
Argh. It is broken again... and (import chicken) doesn't solve the problem anymore.

**Comment by zilti** [comment]
Ok. *NOW* it's solved.
